# Generated by Django 3.2.7 on 2021-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
