# Generated by Django 3.2.7 on 2021-09-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0002_alter_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='parent', to='drive.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
