# Generated by Django 3.2.7 on 2021-09-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20210921_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parents',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='drive.folder'),
        ),
    ]
