# Generated by Django 3.2.7 on 2021-09-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_alter_folder_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parents',
            field=models.OneToOneField(blank=True, default='main', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='drive.folder'),
        ),
    ]
