# Generated by Django 3.2.7 on 2021-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_auto_20210922_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_starred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_starred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
