# Generated by Django 3.2.7 on 2021-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_auto_20210929_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
